name: My FastApi Dev Workflow
on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]
env:
  GITHUB_SHA: ${{ github.sha }}
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  RUN_REGION: us-central1
  SERVICE_NAME: my-fastapi-dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code into workspace directory
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: coverage run -m pytest -s
      - name: Generate the code coverage html
        run: coverage html
      - name: Upload coverage to codecov
        shell: pwsh
        run: |
          coverage report -m  
          codecov --token=${{ secrets.CODECOV_TOKEN }}
      - name: Setup gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
          with:
            version: '290.0.1'
            service_account_key: ${{ secrets.RUN_SA_KEY }}
            project_id: ${{ secrets.RUN_PROJECT }}
      - name: Build and push image to Google Container Registry
        run: |-
          gcloud builds submit \
            --quiet \
            --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"
      - name: Deploy image to Cloud Run
        run: |-
          gcloud run deploy "$SERVICE_NAME" \
            --quiet \
            --region "$RUN_REGION" \
            --image  "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"
            --platform "managed" \
            --allow-unauthenticated
